export type ExpDataType = {
  title: string;
  startDate: string;
  endDate: null | string;
  company: string;
  companyUrl: string;
  logo: string;
  brief: string;
};
export const ExperienceData: ExpDataType[] = [
  {
    title: "Software Engineer",
    startDate: "July 2022",
    endDate: null,
    company: "Apply Digital ULC",
    logo: "/apply_blue_stacked.png",
    companyUrl: "https://www.applydigital.com/",
    brief: `Currently leading a Next.js Identity project for a major sports organization, I focus on registration, authentication, data management, privacy, consents, purchase and various other flows using top-notch tools like SAP Gigya, OneTrust, Datadog, and Synacor. 
    With expertise in analytics, accessibillity, and integration of third-party providers, I am actively collaborating on both mobile and web development. 
    As one of the key players, I contribute to the development of multiple backend repos for the project, leveraging REST APIs, Postman, comprehensive documentation, and various testing procedures.
    With a solid foundation in React, React Native, TypeScript, and backend technologies, I’ve contributed to process optimization and knowledge sharing across teams.
    As I approach my next career level, I continue to grow through leadership, communication, and hands-on technical expertise.`,
  },
  {
    title: "React Nativer Developer",
    startDate: "Feb 2022",
    endDate: "June 2022",
    company: "Walletifai Inc",
    logo: "/apply_blue_stacked.png",
    companyUrl: "https://walletifai.com/",
    brief: ` At Walletifai, I contributed to a finance-based banking project providing users with financial assistance, where I was focused as a React Native developer. 
      I contributed well during the initial phase of this tech startup, helping shape the user interface components for native mobile applications within the React Native ecosystem.
      I worked closely with an R&D team, collaborating in daily scrum meetings to review tickets and manage project flow through JIRA. 
      Additionally, I leveraged Restful APIs for Android and iOS integrations, improved front-end performance by optimizing code efficiency, and troubleshot issues to ensure smooth functionality in development and production environments.
    `,
  },
  {
    title: "Mobile Application Developer",
    startDate: "Sept 2021",
    endDate: "Dec 2021",
    company: "NewslyMeApp",
    logo: "/apply_blue_stacked.png",
    companyUrl: "https://www.newsly.me/",
    brief: `At Newsly Technologies Inc., I played a key role in both front-end and back-end development as part of the research and development team.
      My work spanned across multiple technologies including React Native, Python, Redux, and AWS. One of my key contributions was training Amazon Polly to read out news articles, enabling the audio news and content feature for the mobile application.
      I was also actively involved in developing and enhancing application features, collaborating closely with the team to ensure seamless integration and delivery.
      With a strong foundation in full-stack development, I contributed to both client and server-side application development.
    `,
  },
  {
    title: "Associate Software Developer",
    startDate: "Nov 2017",
    endDate: "Nov 2018",
    company: "Corbiz Solutions",
    logo: "/apply_blue_stacked.png",
    companyUrl: "https://www.facebook.com/corbizsolutions/?locale=eu_ES",
    brief: `I contributed significantly to building a strong team to develop a robust CRM platform for our clients. My role involved assisting in the creation of a platform that streamlined client interactions, as well as lead generation and management processes. 
      I developed a user-friendly web interface using JavaScript, HTML, and CSS to enhance communication with clients. 
      Additionally, I supported senior developers and managers in developing and managing databases to store client files and history. I regularly conducted code reviews, ensuring quality standards were met, and updated the interface to incorporate new features and improvements, aligning with the evolving needs of the employer. 
      As a courtesy, I recently helped the team by developing a React-based web application for their new Commerce Institute, further contributing to the company’s growth and initiatives.
    `,
  },
];

export const ExpertiseImageList = [
  {
    logo: "/techicons/nextjs.png",
    alt: "nextjs",
  },
  {
    logo: "/techicons/typescript.png",
    alt: "typescript",
  },
  {
    logo: "/techicons/nodejs.png",
    alt: "nodejs",
  },
  {
    logo: "/techicons/react.png",
    alt: "react",
  },
  {
    logo: "/techicons/sap.png",
    alt: "sap",
  },
];

export const animationData = {
  v: "5.5.6",
  fr: 29.9700012207031,
  ip: 0,
  op: 89.0000036250443,
  w: 51,
  h: 130,
  nm: "Scroll_icon_white",
  ddd: 0,
  assets: [],
  layers: [
    {
      ddd: 0,
      ind: 1,
      ty: 4,
      nm: "Ð¡Ð»Ð¾Ð¹ 6 Outlines",
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: {
          a: 1,
          k: [
            {
              i: { x: 0.433, y: 1 },
              o: { x: 0.717, y: 0.009 },
              t: 0,
              s: [25.179, 30.476, 0],
              to: null,
              ti: null,
            },
            { t: 59.0000024031193, s: [25.179, 52.101, 0] },
          ],
          ix: 2,
        },
        a: { a: 0, k: [0.763, 3.624, 0], ix: 1 },
        s: {
          a: 1,
          k: [
            {
              i: { x: [0.667, 0.667, 0.667], y: [1, 1, 1] },
              o: { x: [0.333, 0.333, 0.333], y: [0, 0, 0] },
              t: 0,
              s: [100, 0, 100],
            },
            {
              i: { x: [0.667, 0.667, 0.667], y: [1, 1, 1] },
              o: { x: [0.333, 0.333, 0.333], y: [0, 0, 0] },
              t: 30,
              s: [100, 100, 100],
            },
            { t: 59.0000024031193, s: [100, 0, 100] },
          ],
          ix: 6,
        },
      },
      ao: 0,
      shapes: [
        {
          ty: "gr",
          it: [
            {
              ind: 0,
              ty: "sh",
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [0.763, 0.763],
                    [0.763, 6.485],
                  ],
                  o: [
                    [0.763, 0.763],
                    [0.763, 6.485],
                  ],
                  v: [
                    [0.763, 0.763],
                    [0.763, 6.485],
                  ],
                  c: false,
                },
                ix: 2,
              },
              nm: "Path 1",
              mn: "ADBE Vector Shape - Group",
              hd: false,
              _render: true,
            },
            {
              ty: "st",
              c: { a: 0, k: [1, 1, 1, 1], ix: 3 },
              o: { a: 0, k: 100, ix: 4 },
              w: { a: 0, k: 1.526, ix: 5 },
              lc: 1,
              lj: 1,
              ml: 4,
              bm: 0,
              nm: "Stroke 1",
              mn: "ADBE Vector Graphic - Stroke",
              hd: false,
              _render: true,
            },
            {
              ty: "tr",
              p: { a: 0, k: [0, 0], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [100, 100], ix: 3 },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
              _render: true,
            },
          ],
          nm: "Group 1",
          np: 2,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: "ADBE Vector Group",
          hd: false,
          _render: true,
        },
      ],
      ip: 0,
      op: 900.000036657751,
      st: 0,
      bm: 0,
      completed: true,
    },
    {
      ddd: 0,
      ind: 2,
      ty: 4,
      nm: "Ð¡Ð»Ð¾Ð¹ 10 Outlines",
      sr: 1,
      ks: {
        o: {
          a: 1,
          k: [
            {
              i: { x: [0.667], y: [1] },
              o: { x: [0.333], y: [0] },
              t: 34,
              s: [0],
            },
            {
              i: { x: [0.667], y: [1] },
              o: { x: [0.333], y: [0] },
              t: 51,
              s: [100],
            },
            { t: 68.0000027696968, s: [0] },
          ],
          ix: 11,
        },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [25.179, 119.784, 0], ix: 2 },
        a: { a: 0, k: [12.971, 7.248, 0], ix: 1 },
        s: { a: 0, k: [100, 100, 100], ix: 6 },
      },
      ao: 0,
      shapes: [
        {
          ty: "gr",
          it: [
            {
              ind: 0,
              ty: "sh",
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [-11.445, -5.722],
                    [0, 5.722],
                    [11.445, -5.722],
                  ],
                  o: [
                    [-11.445, -5.722],
                    [0, 5.722],
                    [11.445, -5.722],
                  ],
                  v: [
                    [-11.445, -5.722],
                    [0, 5.722],
                    [11.445, -5.722],
                  ],
                  c: false,
                },
                ix: 2,
              },
              nm: "Path 1",
              mn: "ADBE Vector Shape - Group",
              hd: false,
              _render: true,
            },
            {
              ty: "st",
              c: { a: 0, k: [1, 1, 1, 1], ix: 3 },
              o: { a: 0, k: 100, ix: 4 },
              w: { a: 0, k: 1.526, ix: 5 },
              lc: 1,
              lj: 1,
              ml: 4,
              bm: 0,
              nm: "Stroke 1",
              mn: "ADBE Vector Graphic - Stroke",
              hd: false,
              _render: true,
            },
            {
              ty: "tr",
              p: { a: 0, k: [12.971, 7.248], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [100, 100], ix: 3 },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
              _render: true,
            },
          ],
          nm: "Group 1",
          np: 2,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: "ADBE Vector Group",
          hd: false,
          _render: true,
        },
      ],
      ip: 34.0000013848484,
      op: 934.0000380426,
      st: 34.0000013848484,
      bm: 0,
      completed: true,
    },
    {
      ddd: 0,
      ind: 3,
      ty: 4,
      nm: "Ð¡Ð»Ð¾Ð¹ 9 Outlines",
      sr: 1,
      ks: {
        o: {
          a: 1,
          k: [
            {
              i: { x: [0.667], y: [1] },
              o: { x: [0.333], y: [0] },
              t: 17,
              s: [0],
            },
            {
              i: { x: [0.667], y: [1] },
              o: { x: [0.333], y: [0] },
              t: 34,
              s: [100],
            },
            { t: 51.0000020772726, s: [0] },
          ],
          ix: 11,
        },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [25.179, 102.284, 0], ix: 2 },
        a: { a: 0, k: [12.971, 7.248, 0], ix: 1 },
        s: { a: 0, k: [100, 100, 100], ix: 6 },
      },
      ao: 0,
      shapes: [
        {
          ty: "gr",
          it: [
            {
              ind: 0,
              ty: "sh",
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [-11.445, -5.722],
                    [0, 5.722],
                    [11.445, -5.722],
                  ],
                  o: [
                    [-11.445, -5.722],
                    [0, 5.722],
                    [11.445, -5.722],
                  ],
                  v: [
                    [-11.445, -5.722],
                    [0, 5.722],
                    [11.445, -5.722],
                  ],
                  c: false,
                },
                ix: 2,
              },
              nm: "Path 1",
              mn: "ADBE Vector Shape - Group",
              hd: false,
              _render: true,
            },
            {
              ty: "st",
              c: { a: 0, k: [1, 1, 1, 1], ix: 3 },
              o: { a: 0, k: 100, ix: 4 },
              w: { a: 0, k: 1.526, ix: 5 },
              lc: 1,
              lj: 1,
              ml: 4,
              bm: 0,
              nm: "Stroke 1",
              mn: "ADBE Vector Graphic - Stroke",
              hd: false,
              _render: true,
            },
            {
              ty: "tr",
              p: { a: 0, k: [12.971, 7.248], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [100, 100], ix: 3 },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
              _render: true,
            },
          ],
          nm: "Group 1",
          np: 2,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: "ADBE Vector Group",
          hd: false,
          _render: true,
        },
      ],
      ip: 17.0000006924242,
      op: 917.000037350176,
      st: 17.0000006924242,
      bm: 0,
      completed: true,
    },
    {
      ddd: 0,
      ind: 4,
      ty: 4,
      nm: "Ð¡Ð»Ð¾Ð¹ 4 Outlines",
      sr: 1,
      ks: {
        o: {
          a: 1,
          k: [
            {
              i: { x: [0.667], y: [1] },
              o: { x: [0.333], y: [0] },
              t: 0,
              s: [0],
            },
            {
              i: { x: [0.667], y: [1] },
              o: { x: [0.333], y: [0] },
              t: 17,
              s: [100],
            },
            { t: 34.0000013848484, s: [0] },
          ],
          ix: 11,
        },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [25.179, 82.784, 0], ix: 2 },
        a: { a: 0, k: [12.971, 7.248, 0], ix: 1 },
        s: { a: 0, k: [100, 100, 100], ix: 6 },
      },
      ao: 0,
      shapes: [
        {
          ty: "gr",
          it: [
            {
              ind: 0,
              ty: "sh",
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [-11.445, -5.722],
                    [0, 5.722],
                    [11.445, -5.722],
                  ],
                  o: [
                    [-11.445, -5.722],
                    [0, 5.722],
                    [11.445, -5.722],
                  ],
                  v: [
                    [-11.445, -5.722],
                    [0, 5.722],
                    [11.445, -5.722],
                  ],
                  c: false,
                },
                ix: 2,
              },
              nm: "Path 1",
              mn: "ADBE Vector Shape - Group",
              hd: false,
              _render: true,
            },
            {
              ty: "st",
              c: { a: 0, k: [1, 1, 1, 1], ix: 3 },
              o: { a: 0, k: 100, ix: 4 },
              w: { a: 0, k: 1.526, ix: 5 },
              lc: 1,
              lj: 1,
              ml: 4,
              bm: 0,
              nm: "Stroke 1",
              mn: "ADBE Vector Graphic - Stroke",
              hd: false,
              _render: true,
            },
            {
              ty: "tr",
              p: { a: 0, k: [12.971, 7.248], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [100, 100], ix: 3 },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
              _render: true,
            },
          ],
          nm: "Group 1",
          np: 2,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: "ADBE Vector Group",
          hd: false,
          _render: true,
        },
      ],
      ip: 0,
      op: 900.000036657751,
      st: 0,
      bm: 0,
      completed: true,
    },
    {
      ddd: 0,
      ind: 5,
      ty: 4,
      nm: "Ð¡Ð»Ð¾Ð¹ 5 Outlines",
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [25.179, 46.542, 0], ix: 2 },
        a: { a: 0, k: [12.208, 22.127, 0], ix: 1 },
        s: { a: 0, k: [100, 100, 100], ix: 6 },
      },
      ao: 0,
      shapes: [
        {
          ty: "gr",
          it: [
            {
              ind: 0,
              ty: "sh",
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [-5.899, -20.6],
                    [0, -20.6],
                    [10.682, -15.817],
                    [10.682, 9.92],
                    [5.899, 20.6],
                    [-10.682, 15.818999999999999],
                    [-10.682, -9.918],
                  ],
                  o: [
                    [0, -20.6],
                    [5.899, -20.6],
                    [10.682, -9.918],
                    [10.682, 15.818999999999999],
                    [-5.899, 20.6],
                    [-10.682, 9.92],
                    [-10.682, -15.817],
                  ],
                  v: [
                    [0, -20.6],
                    [0, -20.6],
                    [10.682, -9.918],
                    [10.682, 9.92],
                    [0, 20.6],
                    [-10.682, 9.92],
                    [-10.682, -9.918],
                  ],
                  c: true,
                },
                ix: 2,
              },
              nm: "Path 1",
              mn: "ADBE Vector Shape - Group",
              hd: false,
              _render: true,
            },
            {
              ty: "st",
              c: { a: 0, k: [1, 1, 1, 1], ix: 3 },
              o: { a: 0, k: 100, ix: 4 },
              w: { a: 0, k: 1.526, ix: 5 },
              lc: 1,
              lj: 1,
              ml: 4,
              bm: 0,
              nm: "Stroke 1",
              mn: "ADBE Vector Graphic - Stroke",
              hd: false,
              _render: true,
            },
            {
              ty: "tr",
              p: { a: 0, k: [12.208, 22.127], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [100, 100], ix: 3 },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
              _render: true,
            },
          ],
          nm: "Group 1",
          np: 2,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: "ADBE Vector Group",
          hd: false,
          _render: true,
        },
      ],
      ip: 0,
      op: 900.000036657751,
      st: 0,
      bm: 0,
      completed: true,
    },
  ],
  markers: [],
  __complete: true,
};
